config/routes.rb
Library::Application.routes.draw do
  resources :subjects do
    collection do
      get 'list'
    end
member do
      get 'listshow'
    end
end

  resources :books do
    collection do
      get 'issuedfree'
    end
    member do
      get 'issueret'
    end
  end

   root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :title, :subjid, :Appsubjid, :Author, :Issuedperson, :Bookissued, :subject_id
  validates :title, :presence => true
belongs_to :subject
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :subject_name
	has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  def issuedfree
    @books = Book.all

    respond_to do |format|
      format.html # IssuedFree.html.erb
      format.json { render json: @books }
    end
  end
  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @subject = @book.subject
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new
    @subject = Subject.all
      respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
@subject = Subject.all
  end
def issueret
    @book = Book.find(params[:id])
@subject = @book.subject
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
    @subject = Subject.all
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to issuedfree_books_path, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
 def updateis
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Boofffk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end
  def listshow
    @subject = Subject.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end
def list
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end
  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/books/111IssuedFree.html.erb
<h1><i>Listing Issued books</i></h1>

<table>
  <tr>
    <th>Title</th>
    <th>Issued To</th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
<% if book.Bookissued == "Issued" %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.Issuedperson %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<h1><i>Listing Free books</i></h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
<% if book.Bookissued == "Free" %>
  <tr>
    <td><%= book.title %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
  </tr>
  <% end %>
<% end %>
</table>
<%= link_to 'Back', books_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit1.html.erb
<h1>Editing book</h1>

<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
<div class="field">
    <%= f.label :Author %><br />
    <%= f.text_field :Author %>
  </div>
<div class="field">
    <%= f.label :subject %><br />
<%#= f.text_field :subjid %>
    <%= f.select :subjid, @subject.map {|p| [p.subject_name,p.id]}%>
</div>
<div class="field">
    <%= f.label :Book_Issued %><br />
<%= f.select :Bookissued, [['Free','Free'],['Issued','Issued']],:html_options => {:onclick =>'hideIssued();'}%>
    <%#= f.text_field :Bookissued %>
  </div>
<div class="field" id = "f1" style="display:none">
    <%= f.label :Issued_Person %><br />
    <%= f.text_field :Issuedperson %>
  </div>
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @book %>
<%= link_to 'Back', books_path %>
<script>
$(function(){
if($('#book_Bookissued').val() == "Issued")
{
$('#f1').show()
}
else
{
$('#book_Issuedperson').val("")
$('#f1').hide()
}
});
$("form").submit(function() {
      if ($('#book_Bookissued').val() == "Issued") {
        if ($('#book_Issuedperson').val() == "") {
          alert("Please enter Issued Person")
          return false
        }
      }
    });
$('#book_Bookissued').live('change',function()
{
if($('#book_Bookissued').val() == "Issued")
{
$('#f1').show()
}
else
{
$('#f1').hide()
}
});
</script>

app/views/books/index (copy).html.erb
<h1><i>Listing books</i></h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/index.html.erb
<html>
  <head>
<style type="text/css" media="screen">
.Aclass
{
font-color:blue;
}
</style>
</head>
<body>
<Center><h1><i>Library Management System</i><h1></Center>
<Center><img src="assets/books.jpg" alt="books" height="225" width="250" /></Center>
<br><br>
<Center><font Style="color:blue;font-size:13px"><img src="assets/book_icon_small.gif" alt="books" height="20" width="25" />&nbsp<%= link_to 'Books', issuedfree_books_path ,:class => 'Aclass'%></font></Center><br>
<Center><font Style="color:blue;font-size:13px"><img src="assets/ExtendScriptToolkit.png" alt="books" height="25" width="30" />&nbsp<%= link_to 'Books by Subject', list_subjects_path ,:class => 'Aclass'%></font></Center>
</body>

app/views/books/issuedfree (copy).html.erb
<h1><i>Listing Issued books</i></h1>

<table>
  <tr>
    <th>Title</th>
    <th>Issued To</th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
<% if book.Bookissued == "Issued" %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.Issuedperson %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<h1><i>Listing Free books</i></h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
<% if book.Bookissued == "Free" %>
  <tr>
    <td><%= book.title %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
  </tr>
  <% end %>
<% end %>
</table>

app/views/books/issuedfree.html.erb
  <head>
<style type="text/css" media="screen">
body
{
background-image:url('../assets/books_main_lgt.jpg');
background-size:400px 400px;
background-repeat: no-repeat;
background-color:#fffffa;
background-position: 50% 65%;
}
</style>
</head>
<body>
<h1><Center><img src="../assets/book_icon_small.gif" alt="books" height="30" width="35" />&nbsp<u><i>Books</i></u></center></h1>
<center>
<h3>Issued Books</h3>
</center>
<table>
  <tr>
    <th style="width:150px">Title</th>
    <th style="width:150px">Author</th>
    <th>Issued To</th>
    <th></th>
  </tr>

<% @books.each do |book| %>
<% if book.Bookissued == "Issued" %>
  <tr>
    <td style="width:250px"><%= book.title %></td>
<td style="width:250px"><%= book.Author %></td>
    <td><%= book.Issuedperson %></td>
    <td><%= link_to 'Return', issueret_book_path(book)%></td>
  </tr>
  <% end %>
<% end %>
</table>
<center>
<h3>Free Books</h3>
</center>
<table>
  <tr>
    <th style="width:250px">Title</th>
    <th style="width:250px">Author</th>
    <th></th>
  </tr>

<% @books.each do |book| %>
<% if book.Bookissued == "Free" %>
  <tr>
    <td style="width:250px"><%= book.title %></td>
    <td style="width:250px"><%= book.Author %></td>
    <td><%= link_to 'Issue', issueret_book_path(book) %></td>
  </tr>
  <% end %>
<% end %>
</table>
<br><br>
<%= link_to 'Home', books_path %>
</body>

app/views/books/issueret.html.erb
<h1>Issue/Return Book</h1>

<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= @book.title %>
  </div>
<div class="field">
    <%= f.label :Author %><br />
    <%= @book.Author %>
  </div>
<div class="field">
    <%= f.label :subject %><br />
<%#= f.text_field :subjid %>
    <%= @subject.subject_name %>
</div>
<div class="field">
    <%= f.label :Book_Issued %><br />
<%= f.select :Bookissued, [['Free','Free'],['Issued','Issued']],:html_options => {:onclick =>'hideIssued();'}%>
    <%#= f.text_field :Bookissued %>
  </div>
<div class="field" id = "f1" style="display:none">
    <%= f.label :Issued_Person %><br />
    <%= f.text_field :Issuedperson %>
  </div>
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', issuedfree_books_path%>
<%= link_to 'Home', books_path %>
<script>
$(function(){
if($('#book_Bookissued').val() == "Issued")
{
$('#f1').show()
}
else
{
$('#f1').hide()
}
});
$("form").submit(function() {
      if ($('#book_Bookissued').val() == "Issued") {
        if ($('#book_Issuedperson').val() == "") {
          alert("Please enter Issued Person")
          return false
        }
      }
    });
$('#book_Bookissued').live('change',function()
{
if($('#book_Bookissued').val() == "Issued")
{
$('#f1').show()
}
else
{
$('#book_Issuedperson').val("")
$('#f1').hide()
}
});
</script>

app/views/books/new1.html.erb
<h1>New book</h1>

<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Author %><br />
    <%= f.text_field :Author %>
  </div>
<div class="field">
    <%= f.label :subject %><br />
<%#= f.text_field :subjid %>
    <%= f.select :subjid, @subject.map {|p| [p.subject_name,p.id]}%>
</div>
<div class="field">
    <%= f.label :Book_Issued %><br />
<%= f.select :Bookissued, [['Free','Free'],['Issued','Issued']],:html_options => {:onclick =>'hideIssued();'}%>
    <%#= f.text_field :Bookissued %>
  </div>
<div class="field" id = "f1" style="display:none">
    <%= f.label :Issued_Person %><br />
    <%= f.text_field :Issuedperson %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>






<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>
<p>
  <b>Subject:</b>
  <%= @subject.subject_name %>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject_name %><br />
    <%= f.text_area :subject_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit (copy).html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <tr>
    <th>Subject name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.subject_name %></td>
    <td><%= link_to 'Show', subject %></td>
    <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
    <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/list.html.erb
<head>
<style type="text/css" media="screen">
body
{
background-image:url('../assets/books_main_lgt.jpg');
background-size:300px 300px;
background-repeat: no-repeat;
background-color:#fffffa;
background-position: 50% 65%;
}
</style>
</head>
<body>
<h1><Center><img src="../assets/ExtendScriptToolkit.png" alt="books" height="40" width="50" />&nbsp<u><i>Books by Subject</i></u></center></h1><br>
<Center>
<table>
  <tr>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= link_to subject.subject_name, listshow_subject_path(subject) %></td>
   </td>
  </tr>
<% end %>
</table>
</Center>
<br />

<%= link_to 'Home', books_path %>
</body>

app/views/subjects/listshow.html.erb
<Center><h2><%=@subject.subject_name%></h2></center>
<p id="notice"><%= notice %></p>
<br>
<h3><i>Listing Issued books</i></h3>

<table>
  <tr>
    <th style="width:150px">Title</th>
    <th style="width:150px">Author</th>
    <th>Issued To</th>
    <th></th>
  </tr>

<% @subject.books.each do |bo| %>
<% if bo.Bookissued == "Issued" %>
  <tr>
     <td style="width:150px"><%= bo.title %></td>
<td style="width:150px"><%= bo.Author %></td>
    <td><%= bo.Issuedperson %></td>
    <td><%= link_to 'Return', issueret_book_path(bo)%></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<h3><i>Listing Free books</i></h3>

<table>
  <tr>
    <th style="width:150px">Title</th>
    <th style="width:150px">Author</th>
    <th></th>
  </tr>
<% @subject.books.each do |bo| %>
<% if bo.Bookissued == "Free" %>
 <tr>
    <td style="width:150px"><%= bo.title %></td>
    <td style="width:150px"><%= bo.Author %></td>
    <td><%= link_to 'Issue', issueret_book_path(bo) %></td>
  </tr>
  <% end %>
<% end %>
</table>

</p>

<%= link_to 'Back', list_subjects_path%>
<%= link_to 'Home', books_path %>

app/views/subjects/new (copy).html.erb
<h1>New subject</h1>

<%= render 'form' %>



<%= link_to 'Back', subjects_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>



<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject name:</b>
  <%= @subject.subject_name %>
</p>
<p>
  <b>Books:</b>
<br>
<h2><i>Listing Issued books</i></h2>

<table>
  <tr>
    <th style="width:150px">Title</th>
    <th style="width:150px">Author</th>
    <th>Issued To</th>
    <th></th>
  </tr>

<% @subject.books.each do |bo| %>
<% if bo.Bookissued == "Issued" %>
  <tr>
     <td style="width:150px"><%= bo.title %></td>
<td style="width:150px"><%= bo.Author %></td>
    <td><%= bo.Issuedperson %></td>
    <td><%= link_to 'Return', issueret_book_path(bo)%></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<h2><i>Listing Free books</i></h2>

<table>
  <tr>
    <th style="width:150px">Title</th>
    <th style="width:150px">Author</th>
    <th></th>
  </tr>
<% @subject.books.each do |bo| %>
<% if bo.Bookissued == "Free" %>
 <tr>
    <td style="width:150px"><%= bo.title %></td>
    <td style="width:150px"><%= bo.Author %></td>
    <td><%= link_to 'Issue', issueret_book_path(bo) %></td>
  </tr>
  <% end %>
<% end %>
</table>

</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>